<?php

/**
 * @file
 * Custom hooks for Orchard Product of the Day.
 */

/**
 * Implements hook_page_attachments().
 */
function orchard_potd_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'orchard_potd/orchard_potd';
}

/**
 * Implements hook_theme().
 */
function orchard_potd_theme($existing, $type, $theme, $path) {
  return [
    'views_view__entity_product_of_the_day__block_1' => [
      'base hook' => 'views',
      'template' => 'views-view--entity-product-of-the-day--block-1'
    ],
    'node__product_of_the_day__teaser' => [
      'base hook' => 'node',
      'template' => 'node--product-of-the-day--teaser'
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function orchard_potd_preprocess_views_view__entity_product_of_the_day__block_1(&$variables) {
  $config = \Drupal::config('orchard_potd.settings');
  $variables['potd_block_title'] = $config->get('block_title');
}
